CREATE TABLE trump (
    TIME TIMESTAMP,
    INTERVAL INTERVAL,
    NUMBER_OF_TWEETS INTEGER,
    PERCENT_POSITIVE REAL
);
CREATE TABLE clinton (
    TIME TIMESTAMP,
    INTERVAL INTERVAL,
    NUMBER_OF_TWEETS INTEGER,
    PERCENT_POSITIVE REAL
);